# Generated by Django 6.0.3 on 2026-03-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calorielog',
            name='category',
            field=models.CharField(choices=[('proteins', 'Proteins'), ('vitamins', 'Vitamins'), ('carbohydrates', 'Carbohydrates')], default='carbohydrates', max_length=20),
        ),
        migrations.AlterField(
            model_name='calorielog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
